Upgrade farao core swe
farao-community/gridcapa-deployment pull request #248
Opened 2023-03-16 09:40 UTC by TheoPascoli

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2023-03-16 16:09 UTC, schwitzguebel approved these changes

2023-03-23 08:38 UTC, WalAmeni requested changes

2023-03-23 08:38 UTC, WalAmeni commented on k8s/bases/swe-idcc/swe-idcc-runner-itools-configmap.yaml
> +      contingency-scenarios-in-parallel: 4
Could you please update the contingerny-scenarios-in-parallel and the preventive-leaves-in-parallel with the previous values ?

2023-03-23 08:38 UTC, WalAmeni commented on k8s/overlays/azure/test/swe-gridcapa-runner-itools-azure-test-configmap.yaml
> +        contingency-scenarios-in-parallel: 4
Could you please update the contingerny-scenarios-in-parallel and the preventive-leaves-in-parallel with the previous values ?

2023-03-24 08:16 UTC, WalAmeni approved these changes

2023-03-24 08:18 UTC, merged